services:
  php:
    build: .
    container_name: collection
    ports:
      - "8020:80"
    volumes:
      - .:/var/www/html
  redis:
    image: redis:7-alpine
    container_name: my_redis
    ports:
      - "6379:6379"